@host=http://192.168.1.152:8080
###
POST /
Content-Type: application/json

{
    "methodName":"time",
    "args":["test"]
}
###
POST /
Content-Type: application/json

{
    "methodName":"error",
    "args":["test"]
}

###
POST /PONG

{
    "methodName":"count",
    "args":["counting"]
}

###
PATCH /yep

{
    "methodName":"count",
    "args":["counting"]
}

###
PATCH /yep

{
    "methodName":"count",
    "args":["counting"]
}

###

POST /
Content-Type: application/json

{
    "methodName":"timeEnd",
    "args":["test"]
}