# start a maildev container
version: "3.6"

services:
   maildev:
    image: dominikserafin/maildev
    container_name: mailler
    ports:
      - "1080:1080"
      - "1025:1025"
    # networks:
    #   - authentication-network
    # healthcheck:
    #   test: wget --spider http://localhost:1080/healthz || exit 1
    #   interval: 2s
    #   retries: 5
    #   start_period: 5s
    #   timeout: 1s