name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: bump patch  version at deno.json
        run: npx jsr bump patch

      - name: Publish package
        run: npx jsr publish