name: Publish
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
      - run: deno test

      - run: npx tsx --test

      - uses: oven-sh/setup-bun@v2
      - run: bun test
